// ============================================================
// Signal Memory Engine
// Stores every signal with rich market context, descriptions,
// and outcome tracking for the Research Agent to analyze.
// ============================================================

import { supabase } from './supabase.js';
import { logger } from './logger.js';

/**
 * Generate a human-readable description of a signal
 */
export function describeSignal(signal, marketCtx = {}) {
  const { symbol, side, strategy, timeframe, confidence, entry_price, stop_loss, take_profit } = signal;
  const confPct = Math.round((confidence || 0) * 100);
  const tp = Array.isArray(take_profit) ? take_profit[0] : take_profit;
  const rr = stop_loss && tp ? Math.abs((tp - entry_price) / (entry_price - stop_loss)).toFixed(2) : 'N/A';
  
  let desc = `${side} ${symbol} — ${strategy} on ${timeframe}. `;
  desc += `Confidence: ${confPct}%. `;
  desc += `Entry: ${entry_price?.toFixed ? entry_price.toFixed(2) : entry_price}. `;
  
  if (stop_loss) desc += `Stop: ${typeof stop_loss === 'number' ? stop_loss.toFixed(2) : stop_loss}. `;
  if (tp) desc += `Target: ${typeof tp === 'number' ? tp.toFixed(2) : tp}. `;
  desc += `Risk/Reward: ${rr}. `;
  
  // Add market context color
  const rsi = marketCtx.rsi;
  if (rsi !== undefined) {
    desc += `RSI: ${rsi.toFixed(1)} (${rsi > 70 ? 'overbought' : rsi < 30 ? 'oversold' : 'neutral'}). `;
  }
  const change24h = marketCtx.change24h;
  if (change24h !== undefined) {
    desc += `24h change: ${change24h > 0 ? '+' : ''}${change24h.toFixed(2)}%. `;
  }
  const volSpike = marketCtx.volSpike;
  if (volSpike !== undefined) {
    desc += `Volume spike: ${volSpike.toFixed(2)}x avg. `;
  }
  
  return desc.trim();
}

/**
 * Generate entry reason explanation
 */
export function explainEntry(signal, marketCtx = {}) {
  const { side, strategy, confidence, entry_price } = signal;
  const confPct = Math.round((confidence || 0) * 100);
  
  let reasons = [];
  reasons.push(`Signal generated by ${strategy} strategy.`);
  reasons.push(`Confidence score of ${confPct}% meets the minimum threshold.`);
  
  if (strategy.includes('EMA')) {
    const emaFast = marketCtx.ema9 || marketCtx.emaFast;
    const emaSlow = marketCtx.ema21 || marketCtx.emaSlow;
    if (emaFast && emaSlow) {
      reasons.push(`${side === 'LONG' ? 'Bullish' : 'Bearish'} EMA cross detected (${emaFast.toFixed(2)} vs ${emaSlow.toFixed(2)}).`);
    }
  }
  if (strategy.includes('RSI')) {
    const rsi = marketCtx.rsi;
    if (rsi !== undefined) {
      reasons.push(`RSI at ${rsi.toFixed(1)} suggests ${side === 'LONG' ? 'oversold bounce' : 'overbought pullback'} opportunity.`);
    }
  }
  if (strategy.includes('Momentum')) {
    const change24h = marketCtx.change24h;
    if (change24h !== undefined) {
      reasons.push(`${side === 'LONG' ? 'Positive' : 'Negative'} momentum with ${Math.abs(change24h).toFixed(2)}% 24h change.`);
    }
  }
  
  const volSpike = marketCtx.volSpike;
  if (volSpike !== undefined && volSpike > 1.5) {
    reasons.push(`Volume spike of ${volSpike.toFixed(2)}x confirms momentum.`);
  }
  
  reasons.push(`Entry price ${entry_price?.toFixed ? entry_price.toFixed(2) : entry_price} aligns with current market structure.`);
  
  return reasons.join(' ');
}

/**
 * Store a signal in Signal Memory
 */
export async function storeSignalMemory(signal, marketCtx = {}) {
  try {
    const description = describeSignal(signal, marketCtx);
    const entryReason = explainEntry(signal, marketCtx);
    
    const tp = Array.isArray(signal.take_profit) ? signal.take_profit[0] : signal.take_profit;
    const rr = signal.stop_loss && tp && signal.entry_price
      ? Math.abs((tp - signal.entry_price) / (signal.entry_price - signal.stop_loss))
      : null;
    
    const payload = {
      signal_id: signal.id,
      symbol: signal.symbol,
      side: signal.side,
      entry_price: signal.entry_price,
      stop_loss: signal.stop_loss,
      take_profit: Array.isArray(signal.take_profit) ? signal.take_profit : signal.take_profit ? [signal.take_profit] : null,
      confidence: signal.confidence,
      strategy: signal.strategy,
      timeframe: signal.timeframe,
      generated_at: signal.generated_at || new Date().toISOString(),
      source: signal.source || 'auto',
      mode: signal.mode || 'paper',
      description,
      entry_reason: entryReason,
      risk_reward: rr,
      market_ctx: marketCtx,
      outcome: 'pending',
    };
    
    const { data, error } = await supabase
      .from('signal_memory')
      .insert(payload)
      .select()
      .single();
    
    if (error) {
      // Duplicate signal_id — update instead
      if (error.code === '23505') {
        const { data: updated } = await supabase
          .from('signal_memory')
          .update({ description, entry_reason, risk_reward: rr, market_ctx: marketCtx, updated_at: new Date().toISOString() })
          .eq('signal_id', signal.id)
          .select()
          .single();
        return { ok: true, data: updated, updated: true };
      }
      throw error;
    }
    
    logger.info(`[SignalMemory] Stored memory for ${signal.symbol} ${signal.side} (${signal.strategy})`);
    return { ok: true, data, updated: false };
  } catch (e) {
    logger.error(`[SignalMemory] Store failed: ${e.message}`);
    return { ok: false, error: e.message };
  }
}

/**
 * Update signal outcome after trade closes
 */
export async function updateSignalOutcome(signalId, outcome, pnl, note = '') {
  try {
    const { error } = await supabase
      .from('signal_memory')
      .update({ outcome, outcome_pnl: pnl, outcome_note: note, updated_at: new Date().toISOString() })
      .eq('signal_id', signalId);
    
    if (error) throw error;
    logger.info(`[SignalMemory] Updated outcome for signal ${signalId}: ${outcome}, PnL: ${pnl}`);
    return { ok: true };
  } catch (e) {
    logger.error(`[SignalMemory] Update outcome failed: ${e.message}`);
    return { ok: false, error: e.message };
  }
}

/**
 * Query signal memory for research agent analysis
 */
export async function querySignalMemory({ symbol, strategy, timeframe, side, outcome, limit = 100, offset = 0 } = {}) {
  try {
    let q = supabase.from('signal_memory').select('*', { count: 'exact' }).order('generated_at', { ascending: false });
    
    if (symbol) q = q.eq('symbol', symbol);
    if (strategy) q = q.eq('strategy', strategy);
    if (timeframe) q = q.eq('timeframe', timeframe);
    if (side) q = q.eq('side', side);
    if (outcome) q = q.eq('outcome', outcome);
    
    q = q.range(offset, offset + limit - 1);
    
    const { data, error, count } = await q;
    if (error) throw error;
    
    return { ok: true, data: data || [], count, limit, offset };
  } catch (e) {
    logger.error(`[SignalMemory] Query failed: ${e.message}`);
    return { ok: false, error: e.message, data: [] };
  }
}

/**
 * Get strategy performance summary from signal memory
 */
export async function getStrategyPerformanceFromMemory(strategy, timeframe) {
  try {
    let q = supabase.from('signal_memory').select('outcome, outcome_pnl, side').not('outcome', 'eq', 'pending');
    if (strategy) q = q.eq('strategy', strategy);
    if (timeframe) q = q.eq('timeframe', timeframe);
    
    const { data, error } = await q;
    if (error) throw error;
    
    const trades = data || [];
    const wins = trades.filter(t => t.outcome === 'win').length;
    const losses = trades.filter(t => t.outcome === 'loss').length;
    const totalPnl = trades.reduce((s, t) => s + (t.outcome_pnl || 0), 0);
    
    return {
      ok: true,
      totalTrades: trades.length,
      wins,
      losses,
      winRate: trades.length > 0 ? wins / trades.length : 0,
      totalPnl,
      avgPnl: trades.length > 0 ? totalPnl / trades.length : 0,
    };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}
