// ============================================================
// Duplicate Strategy Detector
// Creates a deterministic hash of normalized strategy rules so
// the same idea does not get re-added endlessly under new names.
// Also checks against failure memory to avoid regenerating
// known-weak patterns.
// ============================================================

import crypto from 'crypto';
import { db } from './db.js';
import { logger } from '../logger.js';

/**
 * Normalize a strategy rule into a canonical form for hashing.
 * @param {Object} rule — { feature, operator, threshold }
 * @returns {string}
 */
export function normalizeRule(rule) {
  const feature = (rule.feature || '').toLowerCase().trim();
  const operator = (rule.operator || '').toLowerCase().trim();
  const threshold = typeof rule.threshold === 'number' ? Number(rule.threshold.toFixed(4)) : rule.threshold;
  return `${feature}:${operator}:${threshold}`;
}

/**
 * Normalize an array of rules into a canonical string.
 * @param {Array<Object>} rules
 * @returns {string}
 */
export function normalizeRules(rules) {
  if (!rules || !Array.isArray(rules)) return '';
  return rules
    .map(normalizeRule)
    .sort() // order-independent dedup
    .join('|');
}

/**
 * Generate a deterministic hash from normalized rules.
 * @param {Array<Object>} rules
 * @returns {string} — SHA-256 hex digest (first 16 chars)
 */
export function hashRules(rules) {
  const normalized = normalizeRules(rules);
  if (!normalized) return '';
  return crypto.createHash('sha256').update(normalized).digest('hex').slice(0, 16);
}

/**
 * Generate a hash from a strategy proposal object.
 * @param {Object} proposal — { name, description, rules }
 * @returns {string}
 */
export function hashProposal(proposal) {
  const rules = proposal.rules || [];
  const desc = (proposal.description || '').toLowerCase().trim();
  // Include key description terms for extra discrimination
  const descWords = desc.split(/\s+/).filter(w => w.length > 3).sort().join(' ');
  const combined = `${normalizeRules(rules)}|${descWords}`;
  return crypto.createHash('sha256').update(combined).digest('hex').slice(0, 16);
}

/**
 * Check if a strategy hash already exists in the database.
 * @param {string} hash
 * @returns {boolean}
 */
export function isDuplicateHash(hash) {
  if (!hash) return false;
  try {
    const existing = db.prepare(`
      SELECT id FROM strategy_proposals WHERE rules_hash = ?
    `).get(hash);
    return !!existing;
  } catch (e) {
    return false;
  }
}

/**
 * Check if a strategy hash exists in the failure memory.
 * @param {string} hash
 * @returns {Object|null} — failure record if found
 */
export function findInFailureMemory(hash) {
  if (!hash) return null;
  try {
    return db.prepare(`
      SELECT * FROM strategy_failure_memory WHERE rules_hash = ?
    `).get(hash) || null;
  } catch (e) {
    return null;
  }
}

/**
 * Full duplicate check: returns { isDuplicate, failureRecord, hash }.
 * @param {Object} proposal — { name, description, rules }
 * @returns {{isDuplicate:boolean, failureRecord:Object|null, hash:string, reason:string|null}}
 */
export function checkDuplicate(proposal) {
  const hash = hashProposal(proposal);

  // Check existing proposals
  if (isDuplicateHash(hash)) {
    logger.info(`[DEDUP] Duplicate detected: ${proposal.name} (hash=${hash})`);
    return { isDuplicate: true, failureRecord: null, hash, reason: 'Already exists as a proposal' };
  }

  // Check failure memory
  const failure = findInFailureMemory(hash);
  if (failure) {
    logger.info(`[DEDUP] Previously failed strategy detected: ${proposal.name} (hash=${hash}, reason=${failure.failure_reason})`);
    return { isDuplicate: true, failureRecord: failure, hash, reason: `Previously failed: ${failure.failure_reason}` };
  }

  return { isDuplicate: false, failureRecord: null, hash, reason: null };
}

/**
 * Save a rules hash for a strategy proposal.
 * @param {number} proposalId
 * @param {string} hash
 */
export function saveProposalHash(proposalId, hash) {
  if (!hash) return;
  try {
    db.prepare(`
      UPDATE strategy_proposals SET rules_hash = ? WHERE id = ?
    `).run(hash, proposalId);
  } catch (e) {
    logger.warn(`[DEDUP] Failed to save hash for proposal ${proposalId}: ${e.message}`);
  }
}

/**
 * Check if a strategy name follows the composite_ pattern (auto-generated).
 * @param {string} name
 * @returns {boolean}
 */
export function isAutoGeneratedName(name) {
  return /^composite_[0-9a-z]+$/i.test(name);
}
