-- ============================================================
-- Trading Central Brain Schema — xsjprd55
-- Tables for brain signal memory, events, learning reports,
-- and strategy weights.
-- ============================================================

-- Brain signal memory: stores every decision made by the brain
CREATE TABLE IF NOT EXISTS brain_signal_memory (
  id BIGSERIAL PRIMARY KEY,
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL DEFAULT '15m',
  side TEXT CHECK (side IN ('LONG', 'SHORT', 'NEUTRAL', 'CLOSE')),
  entry_price NUMERIC,
  confidence NUMERIC DEFAULT 0,
  strategy TEXT DEFAULT 'brain_central',
  score JSONB,
  risk_verdict TEXT DEFAULT 'PENDING',
  explanation TEXT,
  mode TEXT DEFAULT 'paper' CHECK (mode IN ('paper', 'live')),
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  resolved_pnl NUMERIC,
  metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_brain_signal_memory_symbol ON brain_signal_memory (symbol);
CREATE INDEX IF NOT EXISTS idx_brain_signal_memory_generated_at ON brain_signal_memory (generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_brain_signal_memory_side ON brain_signal_memory (side);
CREATE INDEX IF NOT EXISTS idx_brain_signal_memory_verdict ON brain_signal_memory (risk_verdict);

-- Brain events: telemetry log for all brain activity
CREATE TABLE IF NOT EXISTS brain_events (
  id BIGSERIAL PRIMARY KEY,
  event TEXT NOT NULL,
  payload JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_brain_events_event ON brain_events (event);
CREATE INDEX IF NOT EXISTS idx_brain_events_created_at ON brain_events (created_at DESC);

-- Brain learning reports: generated by the learning cycle
CREATE TABLE IF NOT EXISTS brain_learning_reports (
  id BIGSERIAL PRIMARY KEY,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  total_signals_analyzed INTEGER DEFAULT 0,
  suggestions JSONB DEFAULT '[]',
  summary JSONB DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_brain_learning_reports_generated_at ON brain_learning_reports (generated_at DESC);

-- Brain strategy weights: adaptive weights per strategy/symbol/timeframe
CREATE TABLE IF NOT EXISTS brain_strategy_weights (
  id BIGSERIAL PRIMARY KEY,
  strategy TEXT NOT NULL,
  symbol TEXT NOT NULL,
  timeframe TEXT NOT NULL DEFAULT '15m',
  weight NUMERIC DEFAULT 0.5,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (strategy, symbol, timeframe)
);

CREATE INDEX IF NOT EXISTS idx_brain_strategy_weights_lookup ON brain_strategy_weights (strategy, symbol, timeframe);

-- Enable RLS but allow service_role full access
ALTER TABLE brain_signal_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE brain_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE brain_learning_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE brain_strategy_weights ENABLE ROW LEVEL SECURITY;

-- Service role bypass (safe for internal use)
CREATE POLICY IF NOT EXISTS "service_role_all_brain_signal_memory"
  ON brain_signal_memory FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "service_role_all_brain_events"
  ON brain_events FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "service_role_all_brain_learning_reports"
  ON brain_learning_reports FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "service_role_all_brain_strategy_weights"
  ON brain_strategy_weights FOR ALL TO service_role USING (true) WITH CHECK (true);
